In [1]:
import pandas as pd

In [11]:
data = {"Name" : ["Shiva", "Bala", "Krishna"],
        "Marks" : [85, 56, 100],
        "Average" : ["70%", "75%", "95%"] }

In [13]:
value = pd.DataFrame(data)

In [14]:
value

      Name  Marks Average
0    Shiva     85     70%
1     Bala     56     75%
2  Krishna    100     95%

In [18]:
# Particular Column
value["Name"]

0      Shiva
1       Bala
2    Krishna
Name: Name, dtype: object

In [19]:
# Specific Columns
value[["Name", "Average"]]

      Name Average
0    Shiva     70%
1     Bala     75%
2  Krishna     95%

In [22]:
# filter (return boolean)
value["Name"] == "Krishna"

0    False
1    False
2     True
Name: Name, dtype: bool

In [25]:
# filter 
value[value["Average"] == "75%"]

   Name  Marks Average
1  Bala     56     75%

In [29]:
# Head
value.head(2)

    Name  Marks Average
0  Shiva     85     70%
1   Bala     56     75%

In [79]:
# unique
new_data = {"Name" : ["Shiva", "Ramesh", "Aravind", "Shiva"],
            "Marks" : [90, 100, 85, 90],
            "Average" : ["90%", "75%", "100%", "90%"]}

In [80]:
values = pd.DataFrame(new_data)

In [81]:
values

      Name  Marks Average
0    Shiva     90     90%
1   Ramesh    100     75%
2  Aravind     85    100%
3    Shiva     90     90%

In [74]:
values.Name.unique()

array(['Shiva', 'Ramesh', 'Aravind'], dtype=object)

In [45]:
values.size

12

In [43]:
values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Marks    4 non-null      int64
 2   Average  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

In [46]:
values.describe()

            Marks
count    4.000000
mean    91.250000
std      6.291529
min     85.000000
25%     88.750000
50%     90.000000
75%     92.500000
max    100.000000

In [55]:
#Group by
compare = pd.DataFrame(data)

In [64]:
compare.groupby('Marks').sum(0)

          Name Average
Marks
56        Bala     75%
85       Shiva     70%
100    Krishna     95%

In [68]:
values.sort_values(by = ["Average", "Marks"])

      Name  Marks Average
2  Aravind     85    100%
3    Shiva     90     75%
1   Ramesh    100     75%
0    Shiva     90     90%

In [69]:
values.value_counts()

Name     Marks  Average
Aravind  85     100%       1
Ramesh   100    75%        1
Shiva    90     75%        1
                90%        1
Name: count, dtype: int64

In [75]:
values.drop_duplicates()

      Name  Marks Average
0    Shiva     90     90%
1   Ramesh    100     75%
2  Aravind     85    100%

In [82]:
values

      Name  Marks Average
0    Shiva     90     90%
1   Ramesh    100     75%
2  Aravind     85    100%
3    Shiva     90     90%

In [83]:
values.drop_duplicates(subset = ["Marks"])

      Name  Marks Average
0    Shiva     90     90%
1   Ramesh    100     75%
2  Aravind     85    100%

In [84]:
import pandas as pd

In [104]:
Person = { "Id" : [1, 4, 3],
           "Name" : ["Jo", "Bobby", "Amaran"]}

In [105]:
first = pd.DataFrame(Person)

In [106]:
Person_1 = {"Id" : [1, 4],
            "Name" : ["Thilak", "Bobby"]}

In [107]:
second = pd.DataFrame(Person_1)

In [90]:
merge_value = pd.merge(first, second, on = "Id", how = "inner")

In [97]:
merge_value

   Id Name_x  Name_y
0   1     Jo  Thilak
1   4  Bobby   Bobby

In [108]:
merge_value = pd.merge(first, second, on = "Id", how = "right")

In [109]:
merge_value

   Id Name_x  Name_y
0   1     Jo  Thilak
1   4  Bobby   Bobby

In [122]:
merge_value = pd.merge(first, second, how = "cross")

In [124]:
merge_value

   Id_x  Name_x  Id_y  Name_y
0     1      Jo     1  Thilak
1     1      Jo     4   Bobby
2     4   Bobby     1  Thilak
3     4   Bobby     4   Bobby
4     3  Amaran     1  Thilak
5     3  Amaran     4   Bobby

In [125]:
merge_value.to_json("mock_data.json")

In [118]:
concat_values = pd.concat([first, second], ignore_index = True)

In [119]:
concat_values

   Id    Name
0   1      Jo
1   4   Bobby
2   3  Amaran
3   1  Thilak
4   4   Bobby

In [127]:
concat_values.to_csv("mock_data.csv")

In [128]:
df1 = pd.DataFrame({'A' : [1,2],
                    'B' : [3,4]})

In [132]:
df2 = pd.DataFrame({'A' : [1,3],
                    'C' : [5,6]})

In [133]:
merged = pd.merge(df1, df2, on = 'A')

In [134]:
merged

   A  B  C
0  1  3  5